language: java
install: mvn ${SPARK_VERSION} ${JAVA_VERSION} ${SCALA_PROFILE} -Dmaven.javadoc.skip=true -DskipTests=true -B -V install
script: mvn ${SPARK_VERSION} ${JAVA_VERSION} ${SCALA_PROFILE} -Dmaven.javadoc.skip=true -q -B verify
matrix:
 include:
   # Covers Java 7, Open JDK, and Spark 1.2.1
   - jdk: openjdk7
   # Covers Java 8, Oracle JDK, and Spark 1.3 (for now)
   - jdk: oraclejdk8
     env: SPARK_VERSION=-Dspark.version=1.3.0 JAVA_VERSION=-Djava.version=1.8
   # Covers Scala 2.11
   - jdk: oraclejdk7
     env: SCALA_PROFILE=-Pscala-2.11